Bnh 168 merging sorting and filtering logic for matches
Change-Ahead/bricks-and-hearts pull request #151
Opened 2022-08-19 09:49 UTC by TomHanmer29

Matching now sorts and filters at the same time. The sorting and filtering list on the tenants page now goes through the same method. Unit tests have been updated to reflect this.
![image](https://user-images.githubusercontent.com/43523985/185593077-09e2de51-002c-4185-91a5-6d01d52e1836.png)

2022-08-19 10:04 UTC, oskarwilliams378 requested changes

2022-08-19 10:04 UTC, oskarwilliams378 commented on web/Controllers/TenantController.cs
> +        if (tenants == null /*needs changing to find a way to call this if postcode not found*/)
maybe for this we could throw and catch an error?

2022-08-19 10:04 UTC, oskarwilliams378 commented on web/Controllers/TenantController.cs
> +        [Authorize(Roles = "Admin")]
Weird indentation here :)

2022-08-19 10:04 UTC, oskarwilliams378 commented on web/Controllers/TenantController.cs
> +        if (csvFile == null)
this cannot be null based on the type annotation

2022-08-19 10:04 UTC, oskarwilliams378 commented on web/Controllers/TenantController.cs
> +        for (int i = 0; i < flashResponse.FlashMessages.Count; i++)
Can you change these to all use var

2022-08-19 10:04 UTC, oskarwilliams378 commented on BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs
> +
New line :)

2022-08-19 10:04 UTC, oskarwilliams378 commented on BricksAndHearts.UnitTests/ServiceTests/Tenant/TenantServiceTests.cs
> +using Microsoft.AspNetCore.Mvc;
Not needed

2022-08-19 10:04 UTC, oskarwilliams378 commented on BricksAndHearts.UnitTests/ControllerTests/Tenant/TenantControllerTests.cs
> +using System.Linq;
Not needed

2022-08-19 10:04 UTC, oskarwilliams378 commented on BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTestsBase.cs
>      protected readonly IAdminService AdminService;
You can remove some imports from here now

2022-08-19 10:04 UTC, oskarwilliams378 commented on BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs
>          A.CallTo(() => AdminService.GetLandlordList(landlordListModel)).MustHaveHappened();
Lots of unneeded imports now :)

2022-08-19 10:30 UTC, TomHanmer29 commented on web/Services/TenantService.cs
> +        var sortedTenantQuery = (await SortTenantsByLocationAndFilter(currentProperty.LandlordRequirements, true, currentProperty.Address.Postcode!, 1, 1000000000))!.Take(5);
I dont think so. Currently the pagination is done at the same time as the properties are ordered by distance (This should be changed imo, I'm planning on making a new ticket for it) and then the results from the filters are combined with this using .intersect. If we only take the first 5 results from the sorted query they might not match the filters and then we'd get fewer results than we want.

2022-08-19 10:31 UTC, TomHanmer29 commented on web/Migrations/BricksAndHeartsDbContextModelSnapshot.cs
> +                    b.ToTable("Landlord", (string)null);
I don't think so, was fiddling around with migrations at one point and must have not undone something correctly

2022-08-19 10:35 UTC, TomHanmer29 commented on web/Services/TenantService.cs
> +        var sortedTenantQuery = (await SortTenantsByLocationAndFilter(currentProperty.LandlordRequirements, true, currentProperty.Address.Postcode!, 1, 1000000000))!.Take(5);
(I'm aware the current way of doing it is quite horrible, I just combined my filtering with Claire's sorting/pagination and didn't want to edit her method too much)

2022-08-19 13:56 UTC, oskarwilliams378 commented on web/Services/TenantService.cs
> +        var sortedTenantQuery = (await SortTenantsByLocationAndFilter(currentProperty.LandlordRequirements, true, currentProperty.Address.Postcode!, 1, 1000000000))!.Take(5);
Ahh ok, yes we definitely should do it the other way around

2022-08-19 13:57 UTC, oskarwilliams378 commented on web/Services/TenantService.cs
> +        var sortedTenantQuery = (await SortTenantsByLocationAndFilter(currentProperty.LandlordRequirements, true, currentProperty.Address.Postcode!, 1, 1000000000))!.Take(5);
If you make a new ticket for it I am happy for you to resolve this

2022-08-19 13:58 UTC, oskarwilliams378 commented on web/Controllers/TenantController.cs
> +        if (tenants == null /*needs changing to find a way to call this if postcode not found*/)
Currently this will never be called as tenants will never be null

2022-08-19 14:02 UTC, oskarwilliams378 requested changes

2022-08-19 14:02 UTC, oskarwilliams378 commented on web/Services/TenantService.cs
> +        var tenantQuery = from tenants in _dbContext.Tenants select tenants;
```suggestion
        var tenantQuery = _dbContext.Tenants.AsQueryable;

```

2022-08-19 14:12 UTC, oskarwilliams378 approved these changes

2022-08-19 14:12 UTC, oskarwilliams378 commented on web/Services/TenantService.cs
> +    private async Task<IQueryable<TenantDbModel>?> SortTenantsByLocationAndFilter(HousingRequirementModel filters, bool isMatching, string postalCode, int page, int perPage)
I completely missed that. sure :)

2022-08-23 10:55 UTC, oskarwilliams378 requested changes

2022-08-23 10:55 UTC, oskarwilliams378 commented on web/Controllers/TenantController.cs
> +    public TenantController(ILogger<TenantController> logger, ITenantService tenantService, IPropertyService propertyService, IMailService mailService, ICsvImportService csvImportService)
Could we multiline this please :)

2022-08-23 10:55 UTC, oskarwilliams378 commented on web/Controllers/TenantController.cs
> +using BricksAndHearts.Services;
There are a few code format things in this file, you could run the cleanup file

2022-08-23 10:55 UTC, oskarwilliams378 commented on web/ViewModels/TenantListModel.cs
> +
extra new line

2022-08-23 10:55 UTC, oskarwilliams378 commented on web/ViewModels/TenantListModel.cs
> +
new line

2022-08-23 10:55 UTC, oskarwilliams378 commented on web/Views/Admin/TenantList.cshtml
> +                   pattern="([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})"/
I think we have a constant for this now in constants :)

2022-08-23 10:55 UTC, oskarwilliams378 commented on web/Services/PostcodeService.cs
>          const string postcodePattern =
could we use the value in the constants file instead :)

2022-08-23 11:16 UTC, oskarwilliams378 approved these changes

2022-08-23 11:16 UTC, oskarwilliams378 commented on web/Controllers/TenantController.cs
> +    public TenantController(ILogger<TenantController> logger, ITenantService tenantService,
Could we multiline all of this please

2022-08-23 11:20 UTC, MaxTheComputerer approved these changes

2022-08-23 11:20 UTC, merged