BNH-16 Landlord Sign Up
Change-Ahead/bricks-and-hearts pull request #19
Opened 2022-07-19 10:00 UTC by TomHanmer29

Updated landlord sign up page to be split across several columns. added buttons to move between pages and added 2 new columns to the database for landlord charter status and landlord type based on the fields in the changeAhead landlord sign up form. 
![image](https://user-images.githubusercontent.com/43523985/179723729-e67366db-1e3c-40a9-bd01-67e93a5220d6.png)
![image](https://user-images.githubusercontent.com/43523985/179724164-d1d7d72f-028e-4b7c-ba07-a6233aee5ab5.png)
user inputs are checked for being empty when you move through the pages of the form, and checked for invalid inputs upon form submission.

2022-07-19 10:03 UTC, TomHanmer29 commented
I think my commit history is a bit messy - I tried to clean it up a bit but not really sure it worked. At some point if someone could give me a hand with how to tidy up my commit history that would be very appreciated :)

2022-07-19 14:06 UTC, TomHanmer29 commented
I think I've realised I ended up pulling remote when my branch was behind remote and should have maybe just force pushed (based on chat with ben abt one of Blanca's branches)

2022-07-19 15:27 UTC, BenRamchandani reviewed
Ohh pretty

I've put a couple of comments on. For git I think the approach I'd take is:

* Check out branch
* Soft reset to the point it branched off main (this is not necessarily the same as current main)
    * This kills all the commits, but leaves your working directory
* Add the db model and migration changes and put them in one commit
* Put the rest in another commit
* Check it all works and force push
* Rebase onto main if necessary

I'm happy to help or you can give it a go yourself

2022-07-19 15:27 UTC, BenRamchandani commented on web/Migrations/20220719095559_AddCharterAndLandlordStatusToLandlordAddHasRequestedAdminToUser.cs
> +                defaultValue: false);
This shouldn't be here.. make sure you're rebased onto main and try recreating the migration

2022-07-19 15:27 UTC, BenRamchandani commented on web/Database/LandlordDbModel.cs
> +    public bool CharterStatus { get; set; } = false;
If this is provided by the landlord then we should make that explicit so it's not confused with the admin approval for charter. I'd call it e.g. LandlordProvidedCharterStatus

2022-07-19 15:27 UTC, BenRamchandani commented on web/wwwroot/js/site.js
> +        stepList[stepIterator].className = stepList[stepIterator].className.replace(" active", "");
Same as this I think (though I haven't tested it!)
```suggestion
        stepList[stepIterator].classList.remove("active");

```

2022-07-20 08:50 UTC, BenRamchandani commented on web/Migrations/20220719095559_AddCharterAndLandlordStatusToLandlordAddHasRequestedAdminToUser.cs
> +                defaultValue: false);
It looks like the existing migration 20220718155426_AddHasRequestedAdminToUser is deleted on this branch. Can you bring that back, then regenerate this migration, which then shouldn't be trying to add this column again

2022-07-20 08:53 UTC, BenRamchandani requested changes
Need to sort out the migrations, but otherwise this looks good to me.

From commit message
> added 2 new rows to landlord in database
should be "columns" not rows

2022-07-20 15:46 UTC, merged