BNH-203, 190 and 196 Property form frontend changes
Change-Ahead/bricks-and-hearts pull request #198
Opened 2022-08-25 14:37 UTC by MaxTheComputerer

- Rent now appears with property details so the edit button makes sense
- Added button to edit address
- Added radio for single/multiple units and input for number of occupied units
- Added instructions to description
- Added asterisks

2022-08-25 14:53 UTC, emilypatsko commented
Could you add some screenshots etc. please? :)

2022-08-25 14:59 UTC, MaxTheComputerer commented
> Could you add some screenshots etc. please? :)

Ah sorry I completely forgot - they're added now!

2022-08-25 16:31 UTC, emilypatsko requested changes
I think generally this looks good, but it looks like the diff for some of the files is odd. I think the line endings have changed and it's making it look like much more of the file has changed

2022-08-25 16:31 UTC, emilypatsko commented on web/Controllers/PropertyController.cs
> +            { Property = propertyViewModel, Owner = owner, Images = imageFiles };
```suggestion
        var propertyDetailsModel = new PropertyDetailsViewModel
        {
            Property = propertyViewModel,
            Owner = owner,
            Images = imageFiles 
        };

2022-08-25 16:31 UTC, emilypatsko commented on web/ViewModels/PropertyInput/PropertyInputModelDescription.cs
> +﻿using System.ComponentModel.DataAnnotations;
The diff is making it look like this whole file has changed and I'm not sure why - this happened on one of Claire's PRs earlier and I believe she resolved it with Oskar. May be worth checking with Claire how this was fixed

2022-08-25 16:31 UTC, emilypatsko commented on web/ViewModels/PropertyInput/PropertyInputModelDetails.cs
> +﻿using System.ComponentModel.DataAnnotations;
Seems to have happened for this file too

2022-08-26 08:04 UTC, emilypatsko approved these changes

2022-08-26 08:04 UTC, merged